version: '3'
services:
  db:
    container_name: pg-docker
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=card_data
    ports:
      - "5432:5432"
    volumes:
      - card_data-data:/var/lib/postgresql/data/
    networks:
      - cardnetwork
  api:
    container_name: api
    build: api/
    ports:
      - "8080:8080"
    networks:
      - cardnetwork
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING=postgresql://postgres:docker@db:5432/card_data
    volumes:
      - type: bind
        source: ./api
        target: /src/app
  client:
    container_name: client
    build: client/
    ports:
      - "3000:3000"
    networks:
      - freaky
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./client
        target: /app

networks:
  cardnetwork:
    driver: bridge
  freaky:
    driver: bridge

volumes:
  card_data-data: